apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: nginx:1.27-alpine
          envFrom:
            - configMapRef:
                name: service-2-config
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi