apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-2-services
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/ilhamellyakhahar/appsets.git
        revision: main
        directories:
          - path: development/project-2/*
  template:
    metadata:
      name: 'project-2-{{path.basename}}'
      labels:
        managed-by: applicationset
        source: git-directories
        project: project-2
    spec:
      project: default
      source:
        repoURL: https://github.com/ilhamellyakhahar/appsets.git
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: development-project-2
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true